document.writeln("<html>");
document.writeln("  ");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<title>UNDER CONSTRUCTION</title>");
document.writeln("  <link rel=\'stylesheet\' href=\'color.css\' />");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("document.onmousedown=click");
document.writeln("function click()");
document.writeln("{");
document.writeln("if(event.button==2){alert(\'对不起，您无权查看源代码);}");
document.writeln("if(event.button==3){alert(\'对不起，您无权查看源代码\');}");
document.writeln("}");
document.writeln("</script>");
document.writeln("</head>");
document.writeln("       ");
document.writeln("<body>");
document.writeln("<h2>THIS WEBSITE IS UNDER CONSTRUCTION...</h2>");
document.writeln("<h3>PLEASE WAIT PATIENTLY:)</h3>");
document.writeln("	");
document.writeln("</body>");
document.writeln("</html>");
